apiVersion: batch/v1
kind: CronJob
metadata:
  name: gitops-cron
  namespace: gitops
spec:
  schedule: "*/1 * * * *"  # Runs every 1 minute
  concurrencyPolicy: Forbid  # Ensures only one job runs at a time
  jobTemplate:
    spec:
      backoffLimit: 0  # No retries on failure
      template:
        spec:
          serviceAccountName: gitops-serviceaccount
          containers:
            - name: gitops-operator
              image: gitopsbook/example-operator:v1.0
              command: ["sh", "-e", "-c"]
              args:
                - |
                  git clone https://github.com/batokenms/taye-kubernetes-dynamic-nginx.git /tmp/example &&
                  find /tmp/example -name '*.yaml' -exec kubectl apply -f {} \; &&
                  kubectl rollout restart deployment nginx-deployment -n gitops
          restartPolicy: Never  # Do not restart the container after the job completes
